# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Demo1
                                 A QGIS plugin
 Boilerplate Plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-07-07
        copyright            : (C) 2022 by Heather Hillers
        email                : not an email address
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Demo1 class from file Demo1.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .demo_1 import Demo1
    return Demo1(iface)
